import type { Metadata } from "next";
import localFont from "next/font/local";
import "../styles/globals.scss";
import { AuthProvider } from "./auth-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider> 
      <body
         
        className={` antialiased`}>
          
        {children}

      </body>
      </AuthProvider> 
    </html>
  );
}
